# Generated by Django 4.1.2 on 2022-11-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyunit_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyunit',
            name='address',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='companyunit',
            name='municipality',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='companyunit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyunit',
            name='place',
            field=models.CharField(max_length=60),
        ),
    ]
