# Generated by Django 4.1.2 on 2022-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_name_alter_companyunit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
