# Generated by Django 4.1.2 on 2024-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyunit',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
