# Generated by Django 4.1.2 on 2022-11-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': (('view_company_types', 'Can view company types'),)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_companies', 'Can view companies'),)},
        ),
    ]
