# Generated by Django 4.1.2 on 2022-11-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_admin_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
