# Generated by Django 4.1.2 on 2022-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_item_vattype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vatType',
            field=models.IntegerField(choices=[(20, 'Opsti'), (10, 'Posebni'), (0, 'Bez')], default=20),
        ),
    ]
