# Generated by Django 4.1.2 on 2022-11-30 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_type_alter_companytype_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0006_alter_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(db_column='receipt', on_delete=django.db.models.deletion.CASCADE, to='receipt.receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='companyUnit',
            field=models.ForeignKey(db_column='companyUnit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companyunit'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
