# Generated by Django 4.1.2 on 2022-12-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0007_alter_item_receipt_alter_receipt_companyunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='measurementUnit',
            field=models.CharField(choices=[('KOM', 'Kom'), ('KUT', 'Kut'), ('KG', 'Kg'), ('L', 'L'), ('M', 'M')], default='KOM', max_length=3),
        ),
    ]
