# Generated by Django 4.1.2 on 2022-12-26 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0008_alter_item_measurementunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('closed', models.BooleanField()),
                ('seen', models.BooleanField()),
                ('receipt', models.ForeignKey(db_column='receipt', on_delete=django.db.models.deletion.CASCADE, to='receipt.receipt')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
