# Generated by Django 4.1.2 on 2022-12-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
